### ISSUE TITLE
درخواست‌عضویت

### ISSUE THREAD

**Issue by kehiy** [persianccbook/Join-request#1]
## نام و نام خانوادگی

کیهان علیزاده

---

## چه کتابی می‌خواهید برای ما بنویسید؟

ترجمه NIP های نوستر.

### درباره آن توضیح بدید

نوستر یک پروتکل غیرمتمکز برای ایجاد شبکه های اجمتماعی می باشد. 
---

## کتابتان را تحت چه اجازه‌نامه ای انتشار می‌دهید؟

- [ ] CC-BY-SA (Creative Commons Attribution-ShareAlike
- [X] Creative Commons NonCommercial license (CC NC, CC BY-NC or NC license) 

---
## قوانین
- برای عضویت در کتابخانه باید [قوانین](https://github.com/persianccbook/.github/blob/main/
agreement.md) مارا مطالعه کرده و بپذیرید.

- [X] قوانین را خوانده و می‌پذیرم.

**Comment by metantesan** [comment]
اسم ریپوزیتوری کتاب خودتونو بدید، که ساخته شده و دسترسی لازمو به شما داده بشه.

**Comment by kehiy** [comment]
@metantesan nips-persian
