### ISSUE TITLE
درخواست‌عضویت

### ISSUE THREAD

**Issue by opaip** [persianccbook/Join-request#3]
## علی معینی

---

### درباره آن توضیح بدید

ترجمه مستندات کتابخانه open-cv پایتون (Cv2)

---

## کتابتان را تحت چه اجازه‌نامه ای انتشار می‌دهید؟

- [+ ] CC-BY-SA (Creative Commons Attribution-ShareAlike

---
## قوانین
- برای عضویت در کتابخانه باید [قوانین](https://github.com/persianccbook/.github/blob/main/
agreement.md) مارا مطالعه کرده و بپذیرید.

- [+] قوانین را خوانده و می‌پذیرم.

**Comment by metantesan** [comment]
با درود. کتاب شما در ادرس
https://github.com/persianccbook/python-opencv 
ایجاد شد و دسترسی لازم به حساب کاربرتون داده شد.
مسیر در دسترس عمومی بودن پروژه نیز
 https://persianccbook.github.io/python-opencv/
میباشد.
