### ISSUE TITLE
درخواست‌عضویت

### ISSUE THREAD

**Issue by itsnyxdev** [persianccbook/Join-request#4]
## نام و نام خانوادگی

محمد فلاحی
ایلیا زراره

falahidev
s-eilia-z

---

### درباره آن توضیح بدید

مجموعه آموزشی PHP، تحت عنوان هفت‌خان PHP که شامل آموزش کامل و پیشرفته PHP، فریم‌ورک‌های PHP، دیتابیس و ... خواهد بود. این مجموعه در آینده به صورت کتاب‌های جداگانه و مختلفی منتشر می‌شود.

---

## کتابتان را تحت چه اجازه‌نامه ای انتشار می‌دهید؟

- [ ] CC-BY-SA (Creative Commons Attribution-ShareAlike
- [x] Creative Commons NonCommercial license (CC NC, CC BY-NC or NC license) 

---
## قوانین
- برای عضویت در کتابخانه باید [قوانین](https://github.com/persianccbook/.github/blob/main/
agreement.md) مارا مطالعه کرده و بپذیرید.

- [x] قوانین را خوانده و می‌پذیرم.

**Comment by metantesan** [comment]
درخواست عضویت شما تایید شد و دسترسی های لازم به شما داده شد
